services:
  app:
    image: yoo-nuxt-todo:dev
    init: true
    volumes:
      - type: bind
        source: .
        target: /app
      - /app/node_modules
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    stdin_open: true
    tty: true